#!/bin/bash

export ITERMOCIL_TASKS=("edit" "test-watch")
export READMEGEN_REPO_ROOT="https://github.com/mattriley/node-module-composer"
export READMEGEN_CODE_ROOT="$READMEGEN_REPO_ROOT/blob/master"

export COV_BRANCHES=95
export COV_FUNCTIONS=93
