#!/bin/bash

export PROJECT_NAME="module-composer"
export SRC="./src"
export DATA="./data"
export MODULES="$SRC/modules"
export TESTS="./tests"
export TEST_HELPERS="./test-helpers"
export TEST_WATCH_PATTERN="{$SRC,$TESTS}/**/*.js"
export ESLINT_PATHS=("$SRC" "$TESTS")
export INDEXGEN_PATHS=("$MODULES")
export INDEXGEN_TYPE="cjs"
export ITERMOCIL_TASKS=("edit" "test-watch" "indexgen-watch" "start")
export GITHUB_PAGES_PATH="./docs"
export COV_BRANCHES=100
export COV_LINES=100
export COV_FUNCTIONS=100
export COV_STATEMENTS=100
