#!/bin/bash

export NODE_VERSION="20.2.0"

export DEV_TASKS="edit | test-watch"
export TEST_RUNNER="module-testrunner"
export MODULE_COMPOSER_ENABLED="true"

export COV_STATEMENTS=90
export COV_BRANCHES=90
export COV_FUNCTIONS=90
export COV_LINES=90
