#!/bin/bash

export INDEXGEN_OPTIONS="--type=esm"
export INDEXGEN_PATHS=("./examples/basic/modules")
export ITERMOCIL_TASKS=("edit" "test-watch")
export READMEGEN_REPO_ROOT="https://github.com/mattriley/node-module-composer"
export READMEGEN_CODE_ROOT="$READMEGEN_REPO_ROOT/blob/master"

export COV_BRANCHES=96
