#!/bin/bash

npx c8 \
    --check-coverage \
    --all \
    --include "$SRC" \
    --reporter=text-summary \
    --reporter=lcov \
    --branches 92 \
    --lines 100 \
    --functions 60 \
    --statements 100 \
    ./tasks/test
