#!/bin/bash -i

# Generates README.md
# NOTE: Ensure draw.io is on the PATH.

README="README.md"

# Generate README.md from ejs template.
node ./tasks/readme-gen.js > $README

# Generate table of contents.
npx doctoc --maxlevel 2 $README 

git add $README
